#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Build secrets.local.php from environment variables (GitHub Actions repository secrets).
 * Uses var_export() so values with quotes, slashes, and + are safe in PHP source.
 */

function pinchard_env(string $name, string $default = ''): string
{
	$v = getenv($name);
	return ($v !== false && $v !== '') ? $v : $default;
}

function pinchard_php_str(string $value): string
{
	return var_export($value, true);
}

function pinchard_putenv_block(string $varName, string $phpVarName): array
{
	return [
		"putenv('{$varName}=' . \${$phpVarName});",
		"\$_ENV['{$varName}'] = \${$phpVarName};",
	];
}

$awsKey = pinchard_env('AWS_ACCESS_KEY_ID');
$awsSecret = pinchard_env('AWS_SECRET_ACCESS_KEY');
if ($awsKey === '' || $awsSecret === '') {
	fwrite(STDERR, "Missing required env: AWS_ACCESS_KEY_ID and/or AWS_SECRET_ACCESS_KEY\n");
	exit(1);
}

$region = pinchard_env('AWS_DEFAULT_REGION', 'us-east-1');
$googleMapsKey = pinchard_env('GOOGLE_MAPS_API_KEY');
$mapboxToken = pinchard_env('MAPBOX_ACCESS_TOKEN');

$lines = [
	'<?php',
	'/**',
	' * Generated by GitHub Actions deploy — do not commit.',
	' * Source: repository secrets (Settings → Secrets and variables → Actions).',
	' */',
	'',
	'// AWS',
	'$key = ' . pinchard_php_str($awsKey) . ';',
	'$secret = ' . pinchard_php_str($awsSecret) . ';',
	'$region = ' . pinchard_php_str($region) . ';',
	'',
	...pinchard_putenv_block('AWS_ACCESS_KEY_ID', 'key'),
	...pinchard_putenv_block('AWS_SECRET_ACCESS_KEY', 'secret'),
	...pinchard_putenv_block('AWS_DEFAULT_REGION', 'region'),
];

if ($googleMapsKey !== '') {
	$lines[] = '';
	$lines[] = '// Google Maps JavaScript API (browser key) — index.php photo map';
	$lines[] = '$googleMapsKey = ' . pinchard_php_str($googleMapsKey) . ';';
	array_push($lines, ...pinchard_putenv_block('GOOGLE_MAPS_API_KEY', 'googleMapsKey'));
}

if ($mapboxToken !== '') {
	if (!str_starts_with($mapboxToken, 'pk.')) {
		fwrite(STDERR, "Warning: MAPBOX_ACCESS_TOKEN must be a public token (pk.*); omitting from secrets.local.php.\n");
	} else {
	$lines[] = '';
	$lines[] = '// Mapbox GL public token (pk.*) — maps/';
	$lines[] = '$mapboxToken = ' . pinchard_php_str($mapboxToken) . ';';
	array_push($lines, ...pinchard_putenv_block('MAPBOX_ACCESS_TOKEN', 'mapboxToken'));
	}
}

$lines[] = '';

$out = implode("\n", $lines);
$target = pinchard_env('PINCHARD_SECRETS_OUTPUT', dirname(__DIR__, 2) . '/secrets.local.php');
$targetDir = dirname($target);
if (!is_dir($targetDir) && !mkdir($targetDir, 0700, true) && !is_dir($targetDir)) {
	fwrite(STDERR, "Failed to create directory {$targetDir}\n");
	exit(1);
}
if (file_put_contents($target, $out) === false) {
	fwrite(STDERR, "Failed to write {$target}\n");
	exit(1);
}
